// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdGqWTezUBvJBC8Xuq5MpuvbTtm47hr_c',
    appId: '1:330643514701:web:a824130983325363a70304',
    messagingSenderId: '330643514701',
    projectId: 'hbus-ccbbc',
    authDomain: 'hbus-ccbbc.firebaseapp.com',
    storageBucket: 'hbus-ccbbc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTjkf-KGXTG6Ot4lEjvefIXWedei6eOIQ',
    appId: '1:330643514701:android:825f8ecac2fbaac1a70304',
    messagingSenderId: '330643514701',
    projectId: 'hbus-ccbbc',
    storageBucket: 'hbus-ccbbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBhEpv6-eeflWR6sa2Mn6vZLVXiBwbyeo',
    appId: '1:330643514701:ios:be2bf5ef5513011ba70304',
    messagingSenderId: '330643514701',
    projectId: 'hbus-ccbbc',
    storageBucket: 'hbus-ccbbc.appspot.com',
    iosClientId: '330643514701-6726m4vnvpojkpq8jblgtismkejm10qo.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBhEpv6-eeflWR6sa2Mn6vZLVXiBwbyeo',
    appId: '1:330643514701:ios:4903b15daf92752da70304',
    messagingSenderId: '330643514701',
    projectId: 'hbus-ccbbc',
    storageBucket: 'hbus-ccbbc.appspot.com',
    iosClientId: '330643514701-col0ljes9u5qe5ckb2i75v56c81kfj4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin.RunnerTests',
  );
}
